version: '3' 

services: 
  flexget:  
    image: cpoppema/docker-flexget
    environment:
      - PUID=1000
      - PGID=1000
      - WEB_PASSWD=${FLEXGET_PASS}
      - TORRENT_PLUGIN=transmission
      - TZ=Europe/Madrid
      - FLEXGET_LOG_LEVEL=info
    volumes:
      - ${MOVIES}:/movies
      - ${STORAGE}/flexget/config:/config
    ports:
      - 5050:5050
    restart: unless-stopped
    depends_on:
      - transmission
  transmission:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ${MOVIES}:/movies
      - ${STORAGE}/transmission/config:/config
    ports:
      - 9091:9091
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
    volumes:
      - ${STORAGE}/plex/config:/config
      - ${MOVIES}:/movies
    network_mode: host
    restart: unless-stopped