web_server: yes
variables: 
  - secrets.yml
  - variables.yml

templates:
  transmission-anchor:
    _transmission-host: &transmission-host
      host: transmission
      port: 9091
      username: "{? transmission.user ?}"
      password: "{? transmission.pass ?}"

  transmission-movies:
    transmission:
      <<: *transmission-host
      main_file_only: yes
      include_subs: yes
      path: /movies/

  
  disable-seen-retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed

tasks:
  # task to pull movies from trakt.tv watchlist and add to the movie list
  load-watchlist:
    priority: 1
    trakt_list:
      username: "{? trakt.user ?}"
      list: "{? trakt.list ?}"
      type: movies
      strip_dates: yes
    accept_all: yes
    seen: local  # We don't want accepted movies on this feed to affect actual download feed
    list_add:
      - movie_list: watchlist  # you can call this whatever you want

  # task to download movies from the movie_list
  download-watchlist:
    priority: 10 # run after the movie queue fill task
    discover:
      what:
        - movie_list: watchlist
      from:
        - piratebay:
            category: highres movies
        - limetorrents:
            category: movies
      interval: 1 day
    torrent_alive: 10 # Will reject results with less than 10 seeds
    quality: hdrip+ # Make sure no screeners or cams are downloaded
    list_match:
      from:
        - movie_list: watchlist
    template: transmission-movies

  # task for cleaning up completed transmission torrents
  clean-transmission:
    template: disable-seen-retry # We disable seen plugins in this task since we want to consider every torrent loaded in transmission every time, no matter what has happened in other tasks or this task in the past.
    from_transmission: 
      <<: *transmission-host
    if:
      - transmission_progress == 100: accept
    transmission:
      <<: *transmission-host
      action: remove

  # task for downloading subtitles
  download-subtitles:
    template: disable-seen-retry
    filesystem:
      path: /movies/
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    seen: local
    subliminal:
      languages:
        - "{? subtitles.lang ?}"
      alternatives:
        - "{? subtitles.alt-lang ?}"
      exact_match: yes
      single: no
      providers: [opensubtitles, podnapisi]
      authentication:
        opensubtitles:
          username: "{? opensubtitles.user ?}"
          password: "{? opensubtitles.pass ?}"